[theme]
primaryColor = "#00FFC0"
backgroundColor = "#090F1D"
secondaryBackgroundColor = "#080E1A"
textColor = "#F8FAFC"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
